// src/App.tsx
import React from 'react';
import { Moon, Sun, Sparkles, BookHeart } from 'lucide-react';
import DreamJournal from './components/DreamJournal';
import Navigation from './components/Navigation';

function App() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-indigo-50 to-purple-50">
      <Navigation />
      <main className="container mx-auto px-4 py-8">
        <header className="text-center mb-12">
          <h1 className="text-4xl font-serif text-indigo-900 mb-4 flex items-center justify-center gap-3">
            <Moon className="text-indigo-700" />
            Dreamscape Journal
            <Sparkles className="text-indigo-700" />
          </h1>
          <p className="text-lg text-indigo-700 max-w-2xl mx-auto">
            Explore your inner world through dream journaling. Understanding your dreams
            is a gateway to deeper self-awareness and personal growth.
          </p>
        </header>
        <DreamJournal />
      </main>
    </div>
  );
}

export default App;

// src/App.vue
`<template>
  <div class="min-h-screen starry-bg">
    <Navigation />
    <main class="container mx-auto px-4 py-12">
      <header class="text-center mb-16">
        <h1 class="text-5xl font-normal text-white mb-6 tracking-wide opacity-90 hover:opacity-100 transition-opacity">
          DREAMSCAPE
        </h1>
        <p class="text-lg text-gray-400 max-w-lg mx-auto uppercase tracking-widest text-sm">
          Explore the depths of your unconscious mind through the ancient art of dream interpretation
        </p>
      </header>
      <DreamJournal />
    </main>
  </div>
</template>

<script setup lang="ts">
import { Moon, Sparkles } from 'lucide-vue-next';
import Navigation from './components/Navigation.vue';
import DreamJournal from './components/DreamJournal.vue';
</script>`
